pre commit better. Only runs CS fixer on new/modified files, displays status, and automatically re-adds

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,3 +1,32 @@
 #!/bin/sh
 
-cd ~/html/es/; ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer --config-file=code_sniffer.php_cs -vv fix app/; cd -;
+green='\033[0;32m'
+red='\033[0;31m'
+nc='\033[0m'
+
+changed=`git diff --staged --name-only`
+changed=`echo $changed | tr '\n' ' '`
+
+cd ~/html/es/
+
+fixed=0
+
+for fn in $changed; do
+    if [[ $fn == app/* ]]; then
+        ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer --config-file=code_sniffer.php_cs --quiet fix $fn
+        status=`echo $?`
+
+        case $status in
+            0) echo "  ${green}OK${nc}     $fn ";;
+            1) echo "  ${red}fixed${nc}  $fn "; git add $fn; ((fixed++));;
+            *) echo "  ${red}UNKNOWN ERROR${nc}";;
+        esac
+    fi
+done
+
+cd - > /dev/null
+
+echo "";
+
+#cd ~/html/es/; ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer --config-file=code_sniffer.php_cs -vv fix app/; cd -;
+
